### ISSUE TITLE
Connection - OPC - ProcessSimulator1.1 could not add tag

### ISSUE THREAD

**Issue by XopHeT** [alexor81/Process-Simulator-2-OpenSource#1]
Connection - OPC - ProcessSimulator1.1 не могу добавить тег

**Как повторить?**

1. Создать пустой проект ProcessSimulator;
2. Добавить Connection типа Internal (имя Connection1);
3. Добавить в Internal Connection тег с именем InputMask и типом UINT32;
4. Добавить Connection типа OPC (имя Connection2);
5. В поле "Name" выбрать ProcessSimulator1.1;
6. Установить галку "Use access path", поле "Separator" оставить без изменений;
7. Нажать кнопку "Connect"
8. Нажать кнопку "OK"
9. Добавить тег в коннектор Connection2
10. В окне выбора тегов выбрать Connection1.InputMask и нажать ОК

**Результат:** 
Окно "Communication Manager" перестает реагировать на нажатия, его невозможно закрыть.
Тег в подключение не добавлен.

**Ожидалось:**
В Connection2 добавиться тег InputMask, и программа не зависнет.

**Задача, которую я решаю:**
Нужно сэмулировать Slave - устройство (модуль ввода-вывода), работающее по Modbus-RTU.
Если я правильно понял, то ProcessSimulator  может работать по Modbus только в режиме мастера.
Решение, которое я придумал: использовать OPC - клиент, позволяющий получать данные от OPC-сервер и передавать по Modbus-RTU в режиме Slave.
Планировалось в этой связке использовать ProcessSimulator как OPC-сервер.

С Уважением,
Алексей.

P.S. Спасибо за Вашу работу.

**Comment by alexor81** [comment]
Добрый день, Алексей

Да, при подключении к самому себе по OPC, есть такой глюк. В следующей версии эта возможность будет не доступна. Можно будет подключаться только к другим экземплярам Process Simulator.

Если честно, я не очень понял зачем вообще вам это понадобилось.
Данные любого соединения (Internal, ModbusN) всегда доступны через OPC сервер Process Simulator в котором они созданны. Для этого не нужно создавать OPC client на самого себя.

С уважением,
Александр

**Comment by XopHeT** [comment]
> Данные любого соединения (Internal, ModbusN) всегда доступны через OPC сервер Process Simulator в котором они созданны.

Я этого не знал, и не додумался проверить.
Спасибо!
